config/routes.rb
Crailslist::Application.routes.draw do

  root 'welcome#index'

  resources :categories do
    resources :articles
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  validates :title, presence: true
  validates_length_of :title, :within => 5..30, :too_short => "Title must be at least 5 characters long.", :too_long => "Title length cannot exceed 30 characters."
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @article = Article.new
  end

  def create
    @category = Category.find(params[:category_id])
    @article = Article.new(article_params)
    @article.category = @category

    if @article.save
      redirect_to category_article_path(@category, @article)
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @article = Article.new(article_params)

    if @article.save
      redirect_to category_article_path(@category, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = Article.where(category: @category)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to articles_path
  end

  private
    def category_params
      params.require(:category).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for ([@category, @article]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article: <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Welcome to cRAILSlist!</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.title, article %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'You serious?' } %></td>
  </tr>
  <% end %>
</table>
<br>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', category_articles_path(@category) %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', category_path(@category) %>
<%= link_to 'Edit', edit_category_article_path(@category, @article) %>

app/views/categories/index.html.erb
<h1>Welcome to cRAILSlist!</h1>

<table>
  <tr>
    <th>Title</th>
    <th colspan="2"></th>
  </tr>
  <% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name.capitalize, category %></td>
    <td><%= link_to 'Delete Category', category_path(category), method: :delete, data: { confirm: 'You serious?' } %></td>
  </tr>
  <% end %>
</table>
<br>
<%= link_to 'New category', new_category_path %>

app/views/categories/show.html.erb
<!-- This is our categories/show view. -->
<h1><%= @category.name.capitalize %></h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <!-- Let's try to use a view helper here to make sure we're including the right objects in the @articles variable. -->
  <% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.title, category_article_path(@category, article) %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Edit', edit_category_article_path(@category, article) %></td>
    <td><%= link_to 'Destroy', category_article_path(@category, article), method: :delete, data: { confirm: 'You serious?' } %></td>
  </tr>
  <% end %>
</table>
<br>

<%= link_to 'New Article', new_category_article_path(@category) %>
<%= link_to 'Back', controller: 'categories' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crailslist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'navbar' %>
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<p><%= link_to 'All Categories', controller: 'categories' %></p>
<p><%= link_to 'New Category', new_category_path %></p>